clean_id_files <- function(id_files) {
  # Reconcile the three families of ID files into a single tidy roster
  # keyed on the UIC DNA ID (pattern "UIC####"):
  #
  # FILES: 
  # 
  # broad-study-ids.xlsx = master roster with DNA ID, study_id, mrn, and
  # demographics. Authoritative source for MRN lookup — every sequenced
  # UIC#### has a row here.
  #
  # SK-*.xls = Broad Institute plate manifests. Provide the Broad "Sample ID"
  # (SM-*) <-> UIC collaborator ID mapping, one row per well. Row 1 is the
  # real header, row 2 a descriptor sub- header, data begins row 3. Three of
  # the nine columns share the label "Alias" and must be renamed on read.
  #
  # redcap-ids.csv = REDCap export with numeric dna_id padded here into
  # UIC####. Used as a cross-check only: a handful of dna_id values map to two
  # different MRNs in REDCap, so it is not safe to fall back on for the
  # authoritative join.
  # 
  # wes-mrn-combined.parquet = WES and MRN mapping. Its all patients with
  # merging the first and second batches to the study_id files. Also contains
  # demographic information. Several WES patients not included in the cluster
  # somehow. Key variables includes *pt_number* which is de-identified.
  #
  # ecg_table.parquet = Log file for all the ECG files. *ecg_number* is the
  # de-identified marker for ECGs, and corresponds to the ECG names in the
  # de-identified WFDB files. The *ecg_name* is supposed to match the ECG name
  # in the de-identified WFDB folder (full ECGs).

  fnames <- basename(id_files)
  broad_master_file <- id_files[fnames == "broad-study-ids.xlsx"]
  redcap_file <- id_files[fnames == "redcap-ids.csv"]
  sk_files <- id_files[grepl("^SK-.*\\.xls$", fnames)]
  cluster_file <- id_files[fnames == "wes-mrn-combined.parquet"]

  # REDCap file and MRN parquet file to recreate dataset
  fnames <- basename(id_files)
  redcap_file <- id_files[fnames == "redcap-ids.csv"]
  cluster_file <- id_files[fnames == "wes-mrn-combined.parquet"]

  # REDCap export: pad numeric dna_id -> UIC####
  # There are duplicate DNA_IDs (matched to multiple MRNs)
  redcap <- 
    vroom::vroom(redcap_file, show_col_types = FALSE) |>
    dplyr::transmute(
      dna_id = sprintf("UIC%04d", dna_id),
      redcap_id = study_id,
      mrn = as.character(mrn)
    ) 

  # Cluster files generated by Darren
  # Has patient number which is needed for ECG data
  ids <- 
    arrow::read_parquet(cluster_file) |>
    janitor::clean_names() |>
    dplyr::select(pt_number, redcap_id = study_id, mrn, cluster_id = record_id, dna_id, broad_id = sample_id) |>
    dplyr::mutate(mrn = as.character(mrn)) |>
    # Currently missing the first batch IDs, but has 2nd batch IDs
    left_join(redcap, by = c("mrn", "redcap_id"), suffix = c("_x", "_y")) |>
    mutate(dna_id = if_else(is.na(dna_id_x), dna_id_y, dna_id_x)) |>
    select(-dna_id_x, -dna_id_y) |>
    mutate(broad_id = if_else(is.na(broad_id), dna_id, broad_id)) 
   
  # Return
  ids

}
