clean_id_files <- function(id_files) {
  # Reconcile the three families of ID files into a single tidy roster
  # keyed on the UIC DNA ID (pattern "UIC####"):
  #
  # FILES: 
  # 
  # broad-study-ids.xlsx = master roster with DNA ID, study_id, mrn, and
  # demographics. Authoritative source for MRN lookup — every sequenced
  # UIC#### has a row here.
  #
  # SK-*.xls = Broad Institute plate manifests. Provide the Broad "Sample ID"
  # (SM-*) <-> UIC collaborator ID mapping, one row per well. Row 1 is the
  # real header, row 2 a descriptor sub- header, data begins row 3. Three of
  # the nine columns share the label "Alias" and must be renamed on read.
  #
  # redcap-ids.csv = REDCap export with numeric dna_id padded here into
  # UIC####. Used as a cross-check only: a handful of dna_id values map to two
  # different MRNs in REDCap, so it is not safe to fall back on for the
  # authoritative join.
  # 
  # wes-mrn-combined.parquet = WES and MRN mapping. Its all patients with
  # merging the first and second batches to the study_id files. Also contains
  # demographic information. Several WES patients not included in the cluster
  # somehow. Key variables includes *pt_number* which is de-identified.
  #
  # ecg_table.parquet = Log file for all the ECG files. *ecg_number* is the
  # de-identified marker for ECGs, and corresponds to the ECG names in the
  # de-identified WFDB files. The *ecg_name* is supposed to match the ECG name
  # in the de-identified WFDB folder (full ECGs).

  fnames <- basename(id_files)
  broad_master_file <- id_files[fnames == "broad-study-ids.xlsx"]
  redcap_file <- id_files[fnames == "redcap-ids.csv"]
  sk_files <- id_files[grepl("^SK-.*\\.xls$", fnames)]
  cluster_file <- id_files[fnames == "wes-mrn-combined.parquet"]

  # Cluster files generated by Darren
  # Has patient number which is needed for ECG data
  id_dat <- 
    arrow::read_parquet(cluster_file) |>
    janitor::clean_names() |>
    dplyr::select(pt_number, redcap_id = study_id, mrn, cluster_id = record_id, dna_id, broad_id = sample_id) |>
    dplyr::mutate(mrn = as.character(mrn))

  # Broad master roster: has MRN keyed on UIC DNA ID
  # Only for the 2nd batch though
  broad_master <- readxl::read_excel(broad_master_file) |>
    dplyr::rename(dna_id = `DNA ID`) |>
    dplyr::mutate(
      dna_id = stringr::str_trim(dna_id),
      mrn = as.character(mrn)
    )

  # REDCap export: pad numeric dna_id -> UIC####. Collapse to one row per
  # dna_id; drop rows where REDCap disagrees with itself on MRN so we do
  # not silently pick a wrong mapping.
  redcap <- vroom::vroom(redcap_file, show_col_types = FALSE) |>
    dplyr::transmute(
      dna_id = sprintf("UIC%04d", dna_id),
      redcap_id = study_id,
      redcap_mrn = as.character(mrn)
    ) |>
    dplyr::group_by(dna_id) |>
    dplyr::filter(dplyr::n_distinct(redcap_mrn) == 1) |>
    dplyr::slice(1) |>
    dplyr::ungroup()

  # Broad plate manifests: Sample ID (SM-*) <-> collaborator UIC DNA ID.
  sk_cols <- c(
    "position", "sample_id",
    "collab_participant_id", "collab_sample_id", "mass",
    "collab_sample_id_2", "gender", "sample_type",
    "collected_after_2015"
  )

  read_sk <- function(f) {
    readxl::read_excel(f, skip = 2, col_names = sk_cols) |>
      dplyr::filter(!is.na(sample_id), !is.na(collab_sample_id)) |>
      dplyr::transmute(
        plate = fs::path_ext_remove(basename(f)),
        position,
        sample_id,
        dna_id = stringr::str_trim(collab_sample_id),
        gender,
        sample_type
      )
  }
  sk <- purrr::map_dfr(sk_files, read_sk)

  # This gets the batch 2 IDs
  # Adds the patient number (pt_number) as well
  # Merge: SK is the denominator (every sample actually sequenced by Broad,
  # including lab controls). Pull MRN and demographics from the master
  # roster; attach REDCap study_id as a cross-reference.
  batch2 <-
    sk |>
    dplyr::left_join(broad_master, by = "dna_id") |>
    # Adds MRN and study IDs
    dplyr::left_join(redcap, by = "dna_id") |>
    dplyr::select(
      dna_id, sample_id, mrn, study_id, redcap_id, redcap_mrn,
      plate, position, gender, sex, ethnicity, age, sample_type
    ) |>
    dplyr::arrange(dna_id) |>
    dplyr::select(dna_id, broad_id = sample_id, mrn, redcap_id = study_id) |>
    dplyr::left_join(id_dat[c("pt_number", "redcap_id", "cluster_id")], by = "redcap_id") 

  # Batch 1 needs DNA IDs to be merged
  # And need to get the "pt_number"
  batch1 <-
    id_dat |>
    dplyr::filter(is.na(dna_id)) |>
    dplyr::select(-dna_id) |>
    dplyr::left_join(redcap, by = "redcap_id") |>
    dplyr::select(-redcap_mrn) |>
    # Character name for matching to samples from genetics
    dplyr::mutate(broad_id = dna_id) 

  # Combine the batches to get a full dataset
  ids <- dplyr::bind_rows(batch1, batch2)

  # Return
  ids

}
